-- MySQL Script generated by MySQL Workbench
-- Mon Jan 23 16:00:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rede_social_lavanderia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rede_social_lavanderia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rede_social_lavanderia` DEFAULT CHARACTER SET utf8 ;
USE `rede_social_lavanderia` ;

-- -----------------------------------------------------
-- Table `rede_social_lavanderia`.`Tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social_lavanderia`.`Tema` (
  `ID_Tema` BIGINT NOT NULL AUTO_INCREMENT,
  `Tipo_tema` VARCHAR(255) NOT NULL,
  `Tema` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_Tema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede_social_lavanderia`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social_lavanderia`.`Usuario` (
  `ID_Usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `Foto` VARCHAR(255) NOT NULL,
  `Nome_completo` VARCHAR(50) NOT NULL,
  `Usuario` VARCHAR(255) NOT NULL,
  `E-mail` VARCHAR(50) NOT NULL,
  `Senha` VARCHAR(50) NOT NULL,
  `Data_nasc` DATE NOT NULL,
  PRIMARY KEY (`ID_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede_social_lavanderia`.`Postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social_lavanderia`.`Postagem` (
  `ID_Postagem` BIGINT NOT NULL AUTO_INCREMENT,
  `Postagem` VARCHAR(2000) NOT NULL,
  `Data_hora` DATETIME(8) NOT NULL,
  `ID_Tema` BIGINT NULL,
  `ID_Usuario` BIGINT NULL,
  PRIMARY KEY (`ID_Postagem`),
  INDEX `fk_Postagem_Tema1_idx` (`ID_Tema` ASC) VISIBLE,
  INDEX `fk_Postagem_Usuario1_idx` (`ID_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Postagem_Tema1`
    FOREIGN KEY (`ID_Tema`)
    REFERENCES `rede_social_lavanderia`.`Tema` (`ID_Tema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postagem_Usuario1`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `rede_social_lavanderia`.`Usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
